### PR TITLE
DO NOT MERGE: Build from git

### PR DESCRIPTION
**Pull request by stuarteberg**
DO NOT MERGE

As discussed in #30, this is just a throw-away PR to build the recipe from the latest commit in git, rather than from a release tarball.  This should help us catch errors in the conda build without waiting for the release.

I also added the `store_build_artifacts` flag, so we should be able to actually download the compiled binaries and test them locally if we want to (assuming the build is successful).

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by stuarteberg** [comment]
If new commits are pushed to the graph-tool master branch, then restart the build here by closing and reopening this PR.

**Comment by stuarteberg** [comment]
The build passed.  However, I think I made a mistake by adding `glib` to the `run` dependencies.  It need only be a build-time `host` dependency.  (And `libglib` will be pulled in automatically via the `cairo` dependency.)  I'm going to push that change now, but if 2.36 is ready-to-go, then there's no harm in just opening a real PR for it.  No need to wait for this build to complete, I think.

---

For reference, the relevant changes to the glib dependency were implemented in these PRs:

- https://github.com/conda-forge/glib-feedstock/pull/57
- https://github.com/conda-forge/cairo-feedstock/pull/55

**Comment by count0** [comment]
2.36 is ready to go... Usually there is an automatic PR that gets created. Is this still the case?

**Comment by stuarteberg** [comment]
>Usually there is an automatic PR that gets created. Is this still the case?

Yes, as far as I know.  But I don't know the bot's schedule.  There's no harm in just creating one manually, as you've done.

**Comment by count0** [comment]
> > Usually there is an automatic PR that gets created. Is this still the case?
> 
> Yes, as far as I know. But I don't know the bot's schedule. There's no harm in just creating one manually, as you've done.

It seems it's every 6 hours...

**Pull request closed without merging**
