### PR TITLE
Bump version to 2.50

### PR DESCRIPTION
**Pull request by count0**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by stuarteberg** [comment]
@conda-forge-admin please rerender

**Comment by count0** [comment]
@stuarteberg After this was merged, the azure pipelines started again from scratch. Given that the full build takes over 5 hours, this seems quite wasteful.

My understanding was that the build artifacts from the MR would be simply be copied over under normal circumstances. Did I misunderstand?

**Comment by count0** [comment]
That's a lot of work... I'm not sure many other packages would benefit from this.

BTW, do you know how much RAM and how many cores the build virtual machines have? We might still be able to squeeze some more from them.

**Comment by stuarteberg** [comment]
I left comments in `build_base.sh`, but they don't point to original references.  Perhaps the situation has changed in the past 4 years.

https://github.com/conda-forge/graph-tool-feedstock/blob/dc1058a72d50f1f304ddf78a2ca7dc21ae5b92d8/recipe/build_base.sh#L37-L40

https://github.com/conda-forge/graph-tool-feedstock/blob/dc1058a72d50f1f304ddf78a2ca7dc21ae5b92d8/recipe/build_base.sh#L66-L73

**Comment by count0** [comment]
It's a bit puzzling, actually, since many of the macOS and linux builds take about the same time to build, although supposedly the macOS images use two jobs, and the linux uses only one. But this could be due to the clang vs GCC difference.

I'll try to up the job counts on both of them to see what happens.

**Comment by count0** [comment]
And BTW, what's up with this ``CPU_COUNT=4`` variable? As far as I can tell it's not doing anything at all, since the job count is controlled by the ``make -j2``. Can this be removed?

**Pull request merged**
