### PR TITLE
Bump version to 2.40

### PR DESCRIPTION
**Pull request by count0**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by count0** [comment]
The tests are giving strange segfaults on import... I haven't seen those anywhere else. @stuarteberg do you have any idea?

**Comment by stuarteberg** [comment]
>The tests are giving strange segfaults on import... I haven't seen those anywhere else. @stuarteberg do you have any idea?

I don't know what could be causing it.  One idea is to attempt to narrow the set of modules to investigate via more fine-grained imports than we [currently use][1]:

[1]: https://github.com/conda-forge/graph-tool-feedstock/blob/master/recipe/meta.yaml#L78-L81

```yaml
test:
  imports:
    - graph_tool
    - graph_tool.all
    - graph_tool.draw
    - graph_tool.draw.cairo_draw
```

Is there any sequence of `import` statements that would introduce modules more incrementally, allowing us to pinpoint the module in which the segfault is occurring?

If we suspect the issue is not in `graph-tool` itself, but rather a corrupt dependency, then I suppose we could just add a slew of imports to that test step before `graph_tool`, attempting to find the bad one:

```yaml
test:
  imports:
    - numpy
    - numpy.linalg
    - scipy
    - scipy.linalg
    - cairo
    - gi
    - gi.repository
    - matplotlib
    - graph_tool
    - graph_tool.all
    - graph_tool.draw
    - graph_tool.draw.cairo_draw
```

Another idea could be to insert the following lines to the top of `graph_tool/__init__.py`.  That way, we'll get a traceback indicating exactly which line (in Python) caused the segfault.

```python
import faulthandler
if not faulthandler.is_enabled():
    faulthandler.enable()
```

You probably [wouldn't want to enable `faulthandler` by default][2] for all graph-tool users, but it could be selectively enabled when `os.environ.get("CONDA_BUILD_STATE") == "TEST"` as [described here][3].

[2]: https://stackoverflow.com/questions/21733856/python-is-there-a-downside-to-using-faulthandler

[3]: https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html#dynamic-behavior-based-on-state-of-build-process

**Comment by count0** [comment]
Let's see if the problem repeats itself. It seems to be happening only on linux, so I agree this is probably unrelated directly to graph-tool.

I will not have time to debug this very soon, so if you want to attempt the tests you suggested, go ahead.

**Comment by stuarteberg** [comment]
Alas, I'm quite busy today.  I won't have time to look into this.

**Comment by count0** [comment]
@stuarteberg could you take a quick look at the logs to see if you notice something obvious?

**Comment by count0** [comment]
Version 2.40 should contain a fix...

**Comment by stuarteberg** [comment]
Well, for mysterious reasons, one configuration took a ridiculously long time to compile.  Judging from the log, it was moments away from finally completing, but the job was killed upon reaching the CI's six hour time limit.

The failed configuration was osx/python-3.9/numpy-1.19.

Personally, I'm inclined to just merge this as-is, and hope that the build succeeds when it is re-run on the master branch merge commit.

**Pull request merged**
