### PR TITLE
ARM OSX Migrator (simplified)

### PR DESCRIPTION
**Pull request by stuarteberg**
Same as #73, but without the "workarounds", based on advice from @isuruf.

### CODE REVIEW

**Comment by stuarteberg** [comment]
@erykoff Would you care to test the build artifacts from this PR?

Same instructions as before, but I updated the artifact link:

1. Go to the [build artifacts listing for our successful build.][1]
2. Download the tarball for your platform.  (If you can't find the Download button, [check out this little video][2].)
3. Unzip the contents (unzip twice since it's a nested zip) and install it to a conda environment:

    ```
    cd ~/Downloads
    unzip conda_artifacts_20220524.8.1_osx_arm64_numpy1.21python3.10.____cpython.zip
    cd conda_artifacts_20220524.8.1_osx_arm64_numpy1.21python3.10.____cpython

    unzip graph-tool-feedstock_conda_artifacts_20220524.8.1_osx_arm64_numpy1.21python3.10.____cpython.zip
    cd graph-tool-feedstock_conda_artifacts_20220524.8.1_osx_arm64_numpy1.21python3.10.____cpython

    conda create -n test-gt -c file://$(pwd) graph-tool-base
    conda activate test-gt
    ```
4. Try a few functions and report back here!

[1]: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=511809&view=artifacts&pathAsName=false&type=publishedArtifacts
[2]: https://imgur.com/a/4YRCTbU

**Comment by erykoff** [comment]
Good news is that it is now 70Mb or so!  And I was able to do `import graph_tool.all` but it gave me warnings that it couldn't import cairo:
```
/Users/erykoff/miniforge3/envs/test-gt2/lib/python3.9/site-packages/graph_tool/draw/cairo_draw.py:32: RuntimeWarning: Error importing cairo. Graph drawing will not work.
```
There may be something wrong with the cairo osx-arm64 build...

**Comment by count0** [comment]
> There may be something wrong with the cairo osx-arm64 build...

What happens if you try importing the cairo module?

**Comment by erykoff** [comment]
Trying to import cairo says module not found, but conda says it's installed.  I don't have time to investigate further at the moment.

**Comment by count0** [comment]
I guess we need to open an issue on pycairo-feedstock.... But as far as I can tell there nothing further we can do on our end. I suppose we can merge this for the time being.

**Review by count0 — APPROVED** [review]

**Comment by stuarteberg** [comment]
Just FYI -- 

>Trying to import cairo says module not found, but conda says it's installed

A colleague of mine was not able to reproduce the error. On an M1 Mac, he tried the following test of `pycairo`:

```
conda create -n pycairo -y -c conda-forge pycairo
$(conda info --base)/envs/pycairo/bin/python -c 'import cairo; print("success")'
```

and `graph_tool`:

```
conda create -n gt -y -c conda-forge graph-tool=2.45
$(conda info --base)/envs/gt/bin/python -c 'import graph_tool.all; print("success")'
```

And both printed `success` with no warnings or errors.

**Pull request merged**
