### PR TITLE
Manual glib migration

### PR DESCRIPTION
**Pull request by xhochy**
Fixes #46 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
Depends on https://github.com/conda-forge/cairomm-feedstock/pull/18

**Comment by stuarteberg** [comment]
@xhochy Shouldn't we bump the build number in this PR?

**Comment by stuarteberg** [comment]
Hmm, conda-forge/cairomm-feedstock#18 was merged, but this PR still fails (`conda.exceptions.UnsatisfiableError`).

**Comment by xhochy** [comment]
Using `conda mambabuild -m .ci_support/osx_64_numpy1.16python3.7.____cpython.yaml recipe` I get the following error:

```
Mamba failed to solve:
 - gtk3
 - llvm-openmp >=11.0.1
 - cairomm-1.0 >=1.12.2
 - pycairo
 - gdk-pixbuf
 - boost >=1.74.0,<1.74.1.0a0
 - zstandard
 - pygobject
 - scipy >=1.0
 - boost-cpp >=1.74.0,<1.74.1.0a0
 - numpy >=1.16.6,<2.0a0
 - librsvg
 - libglib >=2.66.4,<3.0a0
 - python_abi 3.7.* *_cp37m
 - gmp >=6.2.1,<7.0a0
 - gmp >=6.2.1,<7.0a0
 - matplotlib-base
 - python >=3.7,<3.8.0a0
 - expat >=2.2.9,<2.3.0a0
 - expat >=2.2.9,<2.3.0a0
 - libcxx >=11.0.0
 - cairomm
 - sparsehash >=2.0

with channels:

The reported errors are:
⇟   Encountered problems while solving.
   Problem: package pygobject-3.30.5-py36h9043db1_1 requires python_abi 3.6.* *_cp36m, but none of the providers can be installed
   ```
   
   Doesn't really help though.

**Comment by xhochy** [comment]
Waiting for the `libffi` migration on `pygobject` and will then rerun CI.

**Comment by xhochy** [comment]
@conda-forge-admin please restart ci

**Comment by stuarteberg** [comment]
@xhochy This is passing now, but I'll defer to you for merging, in case there's anything you wanted to inspect first.

BTW, thanks for your special attention here, and more generally for the `glib`/`libglib` recipe improvements.

**Review by stuarteberg — APPROVED** [review]

**Pull request merged**
