### PR TITLE
Bump version to 2.37

### PR DESCRIPTION
**Pull request by count0**

### CODE REVIEW

**Comment by stuarteberg** [comment]
I forgot to re-render the feedstock after my last change in #41.  Maybe there's no difference, but  to be on the safe side, it's probably best to do that now, in case a problem is discovered 5 hours from now.

@conda-forge-admin Please rerender

**Comment by count0** [comment]
All tests failed after 80 mins... Is this a new thing?

Will restart to see how far it goes.

**Comment by stuarteberg** [comment]
Strange.  The build in #41 passed.  I don't know why this one would be any different.

**Comment by count0** [comment]
I think I know.... It's a problem with the tarball.

**Comment by count0** [comment]
@conda-forge-admin Please rerender

**Comment by stuarteberg** [comment]
Build succeeded.  Merging now.  The new packages ought to become available on the `conda-forge` channel in 5 hours, when the master branch build succeeds.

**Comment by stuarteberg** [comment]
Here's the build to monitor:
https://github.com/conda-forge/graph-tool-feedstock/runs/1675661438

Or verify that the new packages appear on this page:
https://anaconda.org/conda-forge/graph-tool/files

**Comment by stuarteberg** [comment]
For some reason, one of the builds never completed (osx-py36).  I think it didn't even start properly.  No clue why.

I've re-started the build.  Here's the link:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=260980&view=results

All the other packages built successfully and are already uploaded.

**Comment by count0** [comment]
Ok great. Although not completely warts free yet, things are getting much smoother (and this time it was mostly my fault with the tarball).

Thanks a lot for all the help with this! I think it's great that users can get a full-featured graph-tool via conda now.

**Comment by stuarteberg** [comment]
>Although not completely warts free yet, things are getting much smoother

Yeah, I'm not sure why that one build failed.  I'm not a conda-forge developer, so some aspects of this system are still somewhat mysterious to me.

At least the ability to test with the git repo gives us extra assurance that upcoming releases will build.  I'll close #41 for now, but we ought to repeat that procedure in advance of the next release.

After seeing the `glib` surprise in #41, I guess the most likely cause of errors in the future will be changes to our dependencies' recipes.  We're implicitly exposed to such changes via the [`conda-forge-pinning` feedstock][1], which specifies the versions of all dependencies we don't explicitly pin down ourselves.  There's always a chance something has changed (and possibly broken) in the months since the previous graph-tool release.

[1]: https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml

>I think it's great that users can get a full-featured graph-tool via conda now.

Me too!  I think there are still a few enhancements we could make to the recipe itself, e.g. #28.  (I would personally benefit from that change, so I may implement it soon.)

Also, #29 (and #27) is likely to continue causing confusion for some linux users, unless some nice resolution is implemented in the gtk3 recipe for [this issue][2].  Until then, users who don't already have Xorg libraries installed on their machine will need to install them explicitly, either via their OS package manager or via conda (e.g. as [described in #27][3]).  It might be worth adding a note to the graph-tool docs.

[2]: https://github.com/conda-forge/gtk3-feedstock/issues/7
[3]: https://github.com/conda-forge/graph-tool-feedstock/issues/27#issuecomment-659321036

**Pull request merged**
