### PR TITLE
Attempt microarch build

### PR DESCRIPTION
**Pull request by count0**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by stuarteberg** [comment]
It seems I was mistaken about the ability to cross-compile, at least with this mechanism.  We may need to ask for help or clarification.

**Comment by count0** [comment]
If each builder would cross-compile to all microarchs this would certainly blow the 6h time limit... So, the only viable alternative would be to have one builder per microarch, but that would mean more than a hundred builders. So, I'm not sure this will work.

**Comment by stuarteberg** [comment]
Yeah, the docs do say:

>Adding microarchitecture variants can result in too many entries in the build matrix. Do not overuse it.

One compromise could be to enable the multi-arch build for only recent versions of Python.

**Comment by count0** [comment]
It seems to be going forward.

But there are some issues still:

1.  For aarch64 we get:
```
Error: unrecognized option -march=x86-64-v4
cc1plus: error: unknown value 'x86-64-v4' for '-march'
cc1plus: note: valid arguments are: armv8-a armv8.1-a armv8.2-a armv8.3-a armv8.4-a armv8.5-a armv8.6-a armv8.7-a armv8.8-a armv8-r armv9-a
```
so, we need to disable the microarchs for that arch, since it doesn't make sense. How do we do that? (Or maybe we don't need to; see below).

2. I'm seeing things like ``-march=core2 -mtune=haswell -mssse3`` being added to CXXFLAGS, so maybe we do not need to add ``-march=x86-64-vX`` by hand at all?

3. Clang on MacOS is not cooperating. During the configure checks we get:
```
/configure: line 2052: 12563 Illegal instruction: 4  ./conftest$ac_exeext
```
So, the CGAL check is failing since the binary cannot be run.  :-( Can we enforce GCC in this case? Although, the proper solution in this case is to change the test so that only successful compilation is needed, not execution.

4. It seems like ``-O2`` is being appended to CXXFLAGS along the way, but we should have ``-O3``, otherwise the whole thing is moot. Do you know where this override is coming from?

**Comment by stuarteberg** [comment]
>I'm seeing things like -march=core2 -mtune=haswell -mssse3 being added to CXXFLAGS, so maybe we do not need to add -march=x86-64-vX by hand at all?

Right, the `x86_64-microarch-level` package introduces that flag (by placing a script into the build environment's `etc/conda/activate.d/`).  The only time we need to add it by hand is when we declined to install that package in the build environment, i.e. for level 4.


>So, the CGAL check is failing since the binary cannot be run. :-( Can we enforce GCC in this case? Although, the proper solution in this case is to change the test so that only successful compilation is needed, not execution.

I think we need to stick with the conda-provided compiler on osx, which means sticking with clang.  I think the "proper" solution is the best option, even if we need to implement it with a patch.  In fact, we already have a patch for this.  See `meta.yaml`:

```yaml
source:
  patches:
    # When cross-compiling, don't let configure run a CGAL test program.
    # Just trust the location we pass via --with-cgal
    - patches/skip-cgal-check.patch  # [build_platform != target_platform]
```

... so we just need to expand that condition in the "selector":

```yaml
    - patches/skip-cgal-check.patch  # [build_platform != target_platform or microarch_level == 4]
```

(or we could just remove the selector entirely, in which case the patch is always active and the cgal check would never be executed.

>It seems like -O2 is being appended to CXXFLAGS along the way, but we should have -O3, otherwise the whole thing is moot. Do you know where this override is coming from?

I'm not 100% certain about this, but I think it's coming from the following places on linux and mac, respectively:

- https://github.com/conda-forge/ctng-compiler-activation-feedstock/blob/a9b4929bf211696131aabefe02a34f3b75f6ee11/recipe/conda_build_config.yaml#L48-L93
- https://github.com/conda-forge/clang-compiler-activation-feedstock/blob/main/recipe/build.sh#L7

This might sound hacky, but I suppose we could just strip out `O2` and replace it with `O3` in our own build.  Apparently even the [Python feedstock does this under certain configurations.](https://github.com/conda-forge/python-feedstock/blob/3732e621ad28b925e402c3c1d8542bac029920ad/recipe/build_base.sh#L103)

**Comment by count0** [comment]
> BTW, is it even necessary to strip out the `-O2`? From what I've read, one can simply append `-O3` in which case gcc (and presumably clang, too) will just ignore the earlier `-O2` flag.

This is true, but I wasn't sure where exactly `-O2` was being appended... It seemed to be happening at the very end.

**Comment by stuarteberg** [comment]
Apparently I misremembered how that CGAL patch works.  Upon r[eading the actual patch file](https://github.com/conda-forge/graph-tool-feedstock/blob/main/recipe/patches/skip-cgal-check.patch), I see that we need something different.  That patch relies on autoconf's ability to detect cross-compilation.

**Comment by count0** [comment]
OK, good catch. Let's try now.

**Comment by count0** [comment]
It seems the test
```
if [[ "${microarch_level}" == "4" ]]; then
    CXXFLAGS="${CXXFLAGS} -march=x86-64-v4"
fi
```
is being triggerd by the build:
```
osx osx_arm64_numpy1.22python3.8.____cpython
```
But I don't get it...

**Comment by stuarteberg** [comment]
>But I don't get it...

I agree.   I can't figure out why `microarch_level` is defined at all in those build variants, since the selectors in `conda_build_config.yaml` should be eliminating it entirely.  It must be a bug in `conda-build`.  Maybe one workaround might be the following?

```yaml
microarch_level:
  - 1
  - 3  # [unix and x86_64]
  - 4  # [unix and x86_64]
```

**Comment by stuarteberg** [comment]
Meanwhile, the other builds got far enough along that the test step ran, and failed.  We should disable testing entirely for level 4.

**Comment by stuarteberg** [comment]
We need to disable level-4 testing in both `graph-tool-base` and `graph-tool`.

https://github.com/conda-forge/graph-tool-feedstock/pull/140/commits/7285f9e5fe88a402d90cd1bfaf30a9c6ee8ac72e#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aL124-L128

**Comment by count0** [comment]
Will do, but the flag ``-march=x86-64-v4`` is still seeping in for ``osx osx_arm64_numpy1.22python3.8.____cpython`` somehow...

**Comment by stuarteberg** [comment]
Oh we probably have to rerender after making that change to `conda_build_config.yaml`.

@conda-forge-admin please rerender

**Comment by stuarteberg** [comment]
I'm not sure what was taking the bot so long, so I ran the re-render myself.

**Comment by stuarteberg** [comment]
I downloaded some of the built artifacts from this PR, and tried installing them on my own machine (by [following these instructions][1]).  They seem to work as expected!

---

For the record, here's what I did:

[1]: https://github.com/conda-forge/graph-tool-feedstock/issues/64#issuecomment-1136693003

You can see which architecture your machine has via:

```
conda info | grep archspec
```

And you can figure out which `level` that corresponds to using the following table, which I generated [from this file.][2]

[2]: https://github.com/conda-forge/microarch-level-feedstock/blob/main/recipe/conda_build_config.yaml

<details>

<summary>Click here for table of microarch names and levels</summary>

```
   microarchitecture  level   family
0             x86_64      1   x86_64
1             nocona      1   x86_64
2              core2      1   x86_64
3                k10      1   x86_64
4          x86_64_v2      2   x86_64
5            nehalem      2   x86_64
6           westmere      2   x86_64
7        sandybridge      2   x86_64
8          ivybridge      2   x86_64
9          bulldozer      2   x86_64
10        piledriver      2   x86_64
11       steamroller      2   x86_64
12         x86_64_v3      3   x86_64
13           haswell      3   x86_64
14         broadwell      3   x86_64
15           skylake      3   x86_64
16           mic_knl      3   x86_64
17        cannonlake      3   x86_64
18         excavator      3   x86_64
19               zen      3   x86_64
20              zen2      3   x86_64
21              zen3      3   x86_64
22         x86_64_v4      4   x86_64
23    skylake_avx512      4   x86_64
24       cascadelake      4   x86_64
25           icelake      4   x86_64
26    sapphirerapids      4   x86_64
27              zen4      4   x86_64
28           ppc64le      8  ppc64le
29          power8le      8  ppc64le
30          power9le      9  ppc64le
31         power10le     10  ppc64le
```

</details>

I have access to a Mac with a `skylake` CPU (level 3) and a Linux machine with `sapphirerapids` CPU.

On the Mac, I downloaded both a `level3` and `level4` package and tried them both.  As expected, `level4` could NOT be installed on my machine:

```
cd conda_artifacts_20240528.12.1_osx_64_microarch_level4numpy1.26python3.12.____cpython
conda create -n test-gt -c file://$(pwd) 'graph-tool-base=2.68=*402'

...

Could not solve for environment specs
The following package could not be installed
└─ graph-tool-base ==2.68 py312hef4c000_402 is not installable because it requires
   └─ _x86_64-microarch-level 4.*  but there are no viable options
```

But `level3` CAN be installed, and seems to function normally.

On my linux machine, I tried a `level4` package, and it worked.  Just to be sure it actually uses AVX-512, I ran `objdump -d` on `libgraph_tool_inference.so`, and inspected the output [as described here.][3] Indeed, it seems to contain plenty of AVX-512 instructions.

[3]: https://stackoverflow.com/a/50056059/162094

**Comment by stuarteberg** [comment]
PS -- [Here's a useful article][1] (assuming it's correct) detailing which consumer CPUs (including Macs) support AVX-512 and thus could theoretically benefit from a level-4 build.  It's not all that many models.

[1]: https://blog.reyem.dev/post/which-consumer-computers-support-avx-512/

**Comment by count0** [comment]
This is outstanding!

I think we benefit from level 3 substantially, even if level 4 is not widely available.

So, can we merge this?

**Comment by stuarteberg** [comment]
>So, can we merge this?

Sounds good to me…

**Comment by mbargull** [comment]
Adding such builds unconditionally induces unnecessary strain on the infrastructure.
Could you please heed https://conda-forge.org/docs/maintainer/knowledge_base/#microarch
> Before learning how to use it, please read these considerations:
> - Adding microarchitecture variants can result in too many entries in the build matrix. Do not overuse it.
> - These optimized builds should only be used when the performance improvements are significant.
> - Preferrably, the project should rely on runtime dispatch for arch-specific optimizations.
> - If the package is already too large, consider using smaller outputs for the arch-optimized variants.

and reconsider the extend of your approach?

To put things into perspective:
The single run https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=945053&view=results
produced 2GB of package files and occupied about 74h of overall CI time (assuming I summed everything up correctly).

**Comment by stuarteberg** [comment]
@mbargull Happy to reconsider.  I had also been wondering if this would be too much.

Before this PR, this feedstock ordinarily built 20 variants, resulting in ~1GB of storage.  After this PR, that doubled to 40 variants and ~2GB storage.

One option we were considering is to restrict the platforms that get microarch-specific builds:

- `osx_64` should probably only support level 3.  IIUC, I doubt many level-2 Macs are still in use, and very few level-4 MacBooks were ever made.  Eliminates 10 variants.
- Python 3.8 (and perhaps Python 3.9) is old, so maybe we shouldn't bother with extra optimization.  Eliminates 2 (or 4 variants).

That would bring us down to 26 variants in total (~1.3 GB storage).

**Comment by corneliusroemer** [comment]
> osx_64 should probably only support level 3. IIUC, I doubt many level-2 Macs are still in use, and very few level-4 MacBooks were ever made. Eliminates 10 variants. [Edit: See this [wonderful wikipedia page](https://en.wikipedia.org/wiki/List_of_Mac_models_grouped_by_CPU_type#Intel_x86) for details.]

@stuarteberg, beware that Rosetta2 doesn't support AVX (at least until macOS 15=Sequoia, still in beta), so if you build just a v3 for osx-64, there will be issues for those who use an osx-64 environment with Rosetta2.

Only recently, bioconda started adding osx-arm64 builds, so almost all environments that required at least one bioconda package had to use Rosetta2 with osx-64 environments.

**Pull request merged**
