### PR TITLE
Upgrade to v2.33 and skip linux

### PR DESCRIPTION
**Pull request by stuarteberg**
See discussion in #23.

Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by stuarteberg** [comment]
FYI, I've built the linux packages locally, and uploaded them to my personal channel:
https://anaconda.org/stuarteberg/graph-tool/files

Hopefully the Mac build succeeds.

**Comment by stuarteberg** [comment]
I'll merge this now and ask for help from the conda-forge core team to upload the binaries I built locally.

**Comment by stuarteberg** [comment]
Can someone from @conda-forge/core please upload all six `graph-tool` packages from my personal channel?

https://anaconda.org/stuarteberg/graph-tool/files

I'm following the procedure outlined in [cfep-03](https://github.com/conda-forge/cfep/blob/master/cfep-03.md), so I've attached the build logs to this message:

- [linux-build-logs.tar.gz](https://github.com/conda-forge/graph-tool-feedstock/files/4842562/linux-build-logs.tar.gz)
- [osx-build-log.txt.gz](https://github.com/conda-forge/graph-tool-feedstock/files/4842563/osx-build-log.txt.gz) (Warning, when unzipped, this one is a single ~350 MB text file.)

Notes:

- The linux packages were built with `build-locally.py`, so they use the same Docker container that conda-forge uses.
- The Mac packages were built against the MacOSX 10.9 SDK, just like conda-forge uses.

---

**Background:**

As discussed in a [previous PR](https://github.com/conda-forge/graph-tool-feedstock/pull/23#issuecomment-650628151) and [on gitter](https://gitter.im/conda-forge/conda-forge.github.io?at=5ef78d03bb149531edd4c9b4), we can no longer build this package on the conda-forge CI.  The build runs out of memory.  This may be due to recent changes in the Azure CI environment, or maybe we were just getting lucky before.

**Comment by isuruf** [comment]
> The Mac packages were built against the MacOSX 10.9 SDK, just like conda-forge uses.

How did you do this? Did you set `CONDA_BUILD_SYSROOT`?

**Comment by stuarteberg** [comment]
>How did you do this? Did you set `CONDA_BUILD_SYSROOT`?

Yes. Locally, I edited `.ci_support/osx_python3*.yaml`:

```yaml
MACOSX_DEPLOYMENT_TARGET:
- '10.9'
CONDA_BUILD_SYSROOT:
- /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk

...
```

(That's where I installed the SDK on my machine.)

**Comment by stuarteberg** [comment]
FYI -- The binaries for 2.33 are now available to the `conda-forge` channel.

```
$ conda search -c conda-forge graph-tool=2.33 --subdir=linux-64
Loading channels: done
# Name                       Version           Build  Channel
graph-tool                      2.33  py36h08144f3_0  conda-forge
graph-tool                      2.33  py37hf6cfbc6_0  conda-forge
graph-tool                      2.33  py38hed06623_0  conda-forge

$ conda search -c conda-forge graph-tool=2.33 --subdir=osx-64
Loading channels: done
# Name                       Version           Build  Channel
graph-tool                      2.33  py36h37270f1_0  conda-forge
graph-tool                      2.33  py37h17a5e85_0  conda-forge
graph-tool                      2.33  py38hcf531a8_0  conda-forge
```

**Comment by count0** [comment]
Thanks a lot!

Let's keep our eyes open for a way to automatize this.

**Comment by stuarteberg** [comment]
>Let's keep our eyes open for a way to automatize this.

Agreed.  

Note to self: It will *slightly* simplify our local scripts when the following two changes are merged and released:

   - conda-forge/conda-smithy#1350
   - conda-forge/conda-forge-ci-setup-feedstock#107

**Pull request merged**
