### PR TITLE
Bump version to 2.33

### PR DESCRIPTION
**Pull request by count0**
This also reflects the upstream license change to LGPL-v3.

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by count0** [comment]
@stuarteberg The builds have been failing due to lack of memory at first, and then they just hang, for no apparent reason. I had to restart them multiple times through the day. Do you know if anything can be done?

**Comment by stuarteberg** [comment]
Oh bummer.  I didn't realize that.  Since the build is restarted now, I'm not sure if there's a way for me to see the error log on this PR until it fails again.

I notice that the upgrade bot's PR (#22) also encountered an error.  Is it the same error you've been seeing here?

Logs: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=178714&view=results

**Comment by count0** [comment]
Yeah, same thing.

**Comment by stuarteberg** [comment]
I haven't seen this error before.  I've asked for assistance on the conda-forge gitter channel.  In the meantime, I guess I'll try to keep an eye on the build log to see if the moment of failure is consistent across the three linux builds.  Maybe that will be a clue.

Since you mentioned memory errors: As far as you know, is there any subpackage in graph-tool that might require much more RAM to compile than it did in graph-tool-2.32?

**Comment by count0** [comment]
No, nothing substantial changed in that regard.

**Comment by stuarteberg** [comment]
I'm still puzzled.  It looks like all three linux builds haven't made progress in ~20 minutes or so, but they haven't crashed just yet, so maybe they're just stuck on large translation units and they'll resume shortly.

Here's one thing I don't understand: The builds are all still working on the `inference` package, which [we build first, single-threaded.][1]  But strangely, the log outputs are not identical -- they aren't building the files in the same order.  If `make` really is running single-threaded, shouldn't the build order be deterministic?  (The only difference between these three builds is the python version, which presumably shouldn't change the order of the Makefile targets.)

Does that imply that parallel `make` is being used?  That would explain the memory errors.  But how is that happening?

[1]: https://github.com/conda-forge/graph-tool-feedstock/blob/master/recipe/build.sh#L58-L80

I'm still investigating...

**Comment by count0** [comment]
Maybe we should force `make -j1`, instead of the default, which could pick up some environment variable from somewhere.

**Comment by stuarteberg** [comment]
Seems worth a try.  I can't find any evidence that `MAKEFLAGS` is being manipulated by any of the feedstock scripts, but it's difficult to know for sure if it isn't being introduced somewhere.  I have to step away from my desk for a while.  Can you try pushing the (potential) fix?

**Comment by stuarteberg** [comment]
Dang.  Still getting memory errors, despite your changes.  All three linux builds (though not in exactly the same spots).

<details>

<summary>Example error</summary>

```
================================================================================
+ echo '[inference] Starting make'
+ cd src/graph/inference
+ [[ linux-64 == osx* ]]
  CXX      overlap/graph_blockmodel_overlap_exhaustive.lo
  CXX      overlap/graph_blockmodel_overlap_gibbs.lo
  CXX      overlap/graph_blockmodel_overlap_mcmc.lo
  CXX      overlap/graph_blockmodel_overlap_mcmc_bundled.lo
  CXX      overlap/graph_blockmodel_overlap_multicanonical.lo
  CXX      overlap/graph_blockmodel_overlap_multicanonical_multiflip.lo
  CXX      overlap/graph_blockmodel_overlap_multiflip_mcmc.lo
  CXX      overlap/graph_blockmodel_overlap_vacate.lo
  CXX      layers/graph_blockmodel_layers.lo
  CXX      layers/graph_blockmodel_layers_exhaustive.lo
  CXX      layers/graph_blockmodel_layers_gibbs.lo
  CXX      layers/graph_blockmodel_layers_imp.lo
  CXX      layers/graph_blockmodel_layers_mcmc.lo
  CXX      layers/graph_blockmodel_layers_merge.lo
  CXX      layers/graph_blockmodel_layers_multicanonical.lo
  CXX      layers/graph_blockmodel_layers_multicanonical_multiflip.lo
  CXX      layers/graph_blockmodel_layers_multiflip_mcmc.lo
  CXX      layers/graph_blockmodel_layers_overlap.lo
  CXX      layers/graph_blockmodel_layers_overlap_exhaustive.lo
  CXX      layers/graph_blockmodel_layers_overlap_gibbs.lo
  CXX      layers/graph_blockmodel_layers_overlap_mcmc.lo
  CXX      layers/graph_blockmodel_layers_overlap_mcmc_bundled.lo
  CXX      layers/graph_blockmodel_layers_overlap_multicanonical.lo
  CXX      layers/graph_blockmodel_layers_overlap_multicanonical_multiflip.lo
  CXX      layers/graph_blockmodel_layers_overlap_multiflip_mcmc.lo
  CXX      layers/graph_blockmodel_layers_overlap_vacate.lo
  CXX      uncertain/graph_blockmodel_dynamics_epidemics.lo
  CXX      uncertain/graph_blockmodel_dynamics_epidemics_mcmc.lo
  CXX      uncertain/graph_blockmodel_dynamics_epidemics_mcmc_r.lo
  CXX      uncertain/graph_blockmodel_dynamics_cising_glauber.lo
  CXX      uncertain/graph_blockmodel_dynamics_cising_glauber_mcmc.lo
  CXX      uncertain/graph_blockmodel_dynamics_ising_glauber.lo
  CXX      uncertain/graph_blockmodel_dynamics_ising_glauber_mcmc.lo
  CXX      uncertain/graph_blockmodel_dynamics_pseudo_cising.lo
  CXX      uncertain/graph_blockmodel_dynamics_pseudo_cising_mcmc.lo
  CXX      uncertain/graph_blockmodel_dynamics_pseudo_cising_mcmc_h.lo
  CXX      uncertain/graph_blockmodel_dynamics_pseudo_ising.lo
  CXX      uncertain/graph_blockmodel_dynamics_pseudo_ising_mcmc.lo
  CXX      uncertain/graph_blockmodel_dynamics_pseudo_ising_mcmc_h.lo
  CXX      uncertain/graph_blockmodel_measured.lo
  CXX      uncertain/graph_blockmodel_measured_mcmc.lo
  CXX      uncertain/graph_blockmodel_uncertain.lo
  CXX      uncertain/graph_blockmodel_uncertain_marginal.lo
  CXX      uncertain/graph_blockmodel_uncertain_mcmc.lo
  CXX      support/cache.lo
  CXX      support/int_part.lo
  CXX      support/spence.lo
  CXX      graph_inference.lo
  CXX      graph_latent_multigraph.lo
  CXX      graph_modularity.lo
  CXXLD    libgraph_tool_inference.la
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 474, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 465, in execute
    verify=args.verify, variants=args.variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2864, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1995, in build
    cwd=src_dir, stats=build_stats)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 404, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 379, in _func_defaulting_env_to_os_environ
    proc = PopenWrapper(_args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 264, in __init__
    self.out, self.err = self._execute(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 327, in _execute
    self.disk = max(directory_size(disk_usage_dir), self.disk)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 169, in directory_size
    out = subprocess.check_output(command.format(path).split(), stderr=subprocess.PIPE)
  File "/opt/conda/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/opt/conda/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/conda/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/opt/conda/lib/python3.7/subprocess.py", line 1482, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory
```

</details>

**Comment by stuarteberg** [comment]
This is so frustrating.  Our last successful build was for v2.32, a mere four weeks ago (June 1).

- None of our `host` requirements have been upgraded since then.  (Hence, this recipe did not require re-rendering.)
- None of our `build` requirements have changed, either, including the compiler.  (We don't pin them, which I suppose is dangerous, but I just verified that none of them has seen a new version since June 1.)

I guess that implies that 

As a sanity check, I'm going to re-open a PR for a version that previously succeeded (e.g. v2.32), to see if the CI infrastructure still works for us.

**Comment by count0** [comment]
Let's try once more without LTO, but forcing -j1. Without LTO we passed through the inference submodule at least.

But it's pretty obvious we are touching and possibly crossing the resource boundary that is available. This is not very sustainable.

Is there any infrastructure available that allow us to supply our own builds, without relying on azure?

**Comment by stuarteberg** [comment]
OK, based on a suggestion from a core developer, I tried updating the recipe in #24.  But it still failed.

>But it's pretty obvious we are touching and possibly crossing the resource boundary that is available. This is not very sustainable.

Indeed.  Getting this recipe working in the first place required a bit of trial-and-error.  On Linux, we have to use a single thread (at for `inference`) to avoid running out of RAM.  Fortunately, it still finishes in time.  On Mac, we have to use two threads to avoid running out of time.  Fortunately, it still fits in RAM.

>Is there any infrastructure available that allow us to supply our own builds, without relying on azure?

There's no formal infrastructure, but there's at least a [preliminary notion of such a procedure outlined as a conda-forge enhancement proposal][1].  Basically, one of us should build the linux binaries locally and upload them to our own channel.  Then we'll ask a member of the conda-forge core team to copy the packages over to the main channel.  I'm willing to build the linux packages on my machine and handle the requests.

[1]: https://github.com/conda-forge/cfep/blob/master/cfep-03.md

I propose that we continue using conda-forge for the Mac builds, since (1) it still seems to work, and (2) building on Mac in a reproducible way is slightly more difficult, since it isn't simply a docker build.

I've opened a new PR based on this one, which skips the linux configuration.  Tonight, I'll build the linux packages locally and tomorrow I'll ask someone from the core team to upload them for us.

**Comment by count0** [comment]
If the build could be automatized in a simple script, I could make it part of the whole CI build trigger for graph-tool itself. I have a 64 core 128GB RAM machine dedicated to this. Is it anything more than just bump the version and run build-locally.py?

**Comment by stuarteberg** [comment]
>Is it anything more than just bump the version and run build-locally.py?

I think that's pretty much it, except you'll also need to remove [this newly added line][1] from `recipe/meta.yaml`:

[1]: https://github.com/stuarteberg/graph-tool-feedstock-fork/blob/pr25/recipe/meta.yaml#L25

```yaml
  skip: true  # [linux]
```

Otherwise, the recipe won't build at all.

You'll need to build all three linux configurations:

```
python ./build-locally.py linux_python3.6.____cpythontarget_platformlinux-64
python ./build-locally.py linux_python3.7.____cpythontarget_platformlinux-64
python ./build-locally.py linux_python3.8.____cpythontarget_platformlinux-64
```

You may wish to manually set the `CPU_COUNT` environment variable, otherwise the recipe will try to use all 64 cores of your machine.  (If you run the three configurations in parallel, that would be bad.)  IIUC, `conda-build` will respect the `CPU_COUNT` value if you define it in the enclosing environment.  Since conda-build will be running within the docker container, you'll have to add `-e CPU_COUNT=16` to `./scripts/run_docker_build.sh`.

**Comment by stuarteberg** [comment]
Also, I think the packages won't actually be uploaded anywhere.  They will be written to the container's file system, probably in `/opt/conda/conda-bld/linux-64/graph-tool-2.33-*.tar.bz2`. You'll need to use `docker cp` to extract them from the container, and then upload them to your own channel, e.g. `anaconda upload -u count0 /path/to/graph-tool-2.33-*.tar.bz2`

Anyway, something like that, I think.

**Comment by jakirkham** [comment]
Could try using the trick in PR ( https://github.com/conda-forge/conda-smithy/pull/1345 ) to clear some space on the Linux image. We've had issues without doing that in a few places. So might help here too.

**Comment by stuarteberg** [comment]
@jakirkham Thanks for the suggestion.  Isuru already suggested that I try rerendering with `conda-smithy/master`, which already incorporates your PR.  I gave it a try in #24, but it didn't seem to make a difference.

I wonder if something else is going on here.  Even one of my Mac builds seems to have crapped out.  I had to restart #25.

BTW, what's the proper way to extract a built package from the container after running `build_local.py`?

**Comment by stuarteberg** [comment]
>BTW, what's the proper way to extract a built package from the container after running build_local.py?

Nevermind, I see that the docker container already exposes the proper directory outside the container, directly on the host machine in `graph-tool-feedstock/build_artifacts`.

**Pull request merged**
